### PR TITLE
F sync yaml

### PR DESCRIPTION
**Pull request by dg-shadow**

### CODE REVIEW

**Comment by ugocupcic** [comment]
PR is looking good from my side but would rather have someone on site do the real review.

**Comment by dg-shadow** [comment]
Sorry - should have named better - I still need to tune the camera parameters for good quality images. This pr is more to do with the changes to the code to allow the configuration necessary for syncing. Happy to wait till the params are tuned if you prefer though

**Comment by ugocupcic** [comment]
Ah OK! Will merge this one then. The next can be reviewed by other people. Can you include a few images in the next pr when they are tuned out of interest?

**Comment by dg-shadow** [comment]
yes, will include images

**Pull request merged**
